version: '3.8'

services:
  php:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    command: >
      bash -c "apt-get update && apt-get install -y default-mysql-client libpq-dev &&
              docker-php-ext-install pdo pdo_mysql &&
              apache2-foreground"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gerenciamento_academico_completo
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3316:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data:
